### ISSUE TITLE
Compiler warning (32-bit without readline support under Cygwin) 

### ISSUE THREAD

**Issue by alex-konovalov** [gap-system/gap#2745]
There is a new compiler warning when GAP is built in 32-bit mode without readline support under Cygwin with gcc 4.9.2. The original build log is available only within St Andrews network [here](https://gap-ci.cs.st-andrews.ac.uk/view/GAP-nightly/job/GAP-master-compilers/GAPCOPTS=32build,GAPREADLINE=noreadline,label=gcc-cygwin/356/console).
```
/bin/sh ./libtool --mode=compile gcc -std=gnu99 -MQ "obj/src/gap.lo" -MMD -MP -MF "obj/src/.deps/gap.d" -m32 -Werror  -I./gen -I./src -DHAVE_CONFIG_H       -fno-strict-aliasing -Wall -Wextra -Wundef -Wwrite-strings -Wpointer-arith -Wredundant-decls -Wno-unused-parameter -Wmissing-field-initializers -Wformat=2 -Wold-style-definition -Wformat-nonliteral -Wformat-security -Wno-sign-compare -Wstrict-aliasing -Wshadow -Winline -Wpacked -Wmissing-format-attribute -Winit-self -Wmissing-include-dirs -Wunused-but-set-variable -Warray-bounds -Wreturn-type -Wno-implicit-fallthrough -Wno-inline -Wlogical-op -Wdouble-promotion -Wnested-externs -Wimplicit-function-declaration -Wjump-misses-init -Wno-error=unused-parameter -Wno-error=sign-compare -Wno-error=inline  "-DCOMPILECYGWINDLL" -c src/gap.c -o obj/src/gap.lo
libtool: compile:  gcc -std=gnu99 -MQ obj/src/gap.lo -MMD -MP -MF obj/src/.deps/gap.d -m32 -Werror -I./gen -I./src -DHAVE_CONFIG_H -fno-strict-aliasing -Wall -Wextra -Wundef -Wwrite-strings -Wpointer-arith -Wredundant-decls -Wno-unused-parameter -Wmissing-field-initializers -Wformat=2 -Wold-style-definition -Wformat-nonliteral -Wformat-security -Wno-sign-compare -Wstrict-aliasing -Wshadow -Winline -Wpacked -Wmissing-format-attribute -Winit-self -Wmissing-include-dirs -Wunused-but-set-variable -Warray-bounds -Wreturn-type -Wno-implicit-fallthrough -Wno-inline -Wlogical-op -Wdouble-promotion -Wnested-externs -Wimplicit-function-declaration -Wjump-misses-init -Wno-error=unused-parameter -Wno-error=sign-compare -Wno-error=inline -DCOMPILECYGWINDLL -c src/gap.c  -DDLL_EXPORT -DPIC -o obj/src/.libs/gap.o
src/gap.c: In function â€˜FuncFORCE_QUIT_GAPâ€™:
src/gap.c:1327:1: error: control reaches end of non-void function [-Werror=return-type]
 }
 ^
src/gap.c: At top level:
cc1: error: unrecognized command line option "-Wno-implicit-fallthrough" [-Werror]
cc1: all warnings being treated as errors
Makefile.rules:348: recipe for target 'obj/src/gap.lo' failed
make: *** [obj/src/gap.lo] Error 1
Build step 'Execute shell' marked build as failure
```

**Comment by fingolfin** [comment]
That's odd, as that function ends with `SyExit`, which is marked as `NORETURN`, which in turn should work fine on GCC 4.9.2, regardless of 32bit or 64bit build.

It would be interesting to see whether the output of the `configure` script contains the line
```
checking for __attribute__((noreturn))... yes
```
